### ISSUE TITLE
Add explanation of the initial docker run command to the readme

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1350]
- Add explanation of the initial docker run command to the readme
- Also put into the docker-compose why some of the values are not changable
- also update the entrypoint hints accordingly

**Comment by roib20** [comment]
I can help with this. The documentation for for [docker-compose.yml](https://github.com/nextcloud/all-in-one/blob/main/docker-compose.yml) seems mostly complete already; I can add similar comments explaining every value in the `docker run` command, and what can be changed. Also making sure to change correspondent values if necessary in entrypoint files.

Perhaps documentation explaining bind mounts for host ports should be added. My understanding is it should be possible to change ports for the host (even without a reverse proxy), so it is not mandatory to use ports 80, 8443 and 8080 on the host (as long as the bind mounts are done correctly).

One way to potentially make changing values easier is to use an .env file. This way all the values that can be changed could be clearly outlined in one file. However this can be a double-edged since in my experience since new Docker users can sometimes find .env files a bit confusing to work with. It also might not work well in this case, because many of the values are entirely optional.

**Comment by szaimen** [comment]
@roib20 thanks for the offer! I just started with this in https://github.com/nextcloud/all-in-one/pull/1375. Feedback on this is appreciated! See https://github.com/nextcloud/all-in-one/tree/enh/1350/add-explanation-of-docker-run#:~:text=explanation%20of%20the%20command
