### ISSUE TITLE
Nice to have (not urgent)

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#139]
**Nice to have but not urgent**
- [ ] If the default admin user is deleted then the login data is still in the AIO backend, is not really urgent but would be great if this is changed at some point.
- [ ] In the AIO backend, instead of the NC logo, the own logo customized in the design.

**Comment by szaimen** [comment]
I fear both requests are out of scope since 1. there is no way for us to find out if a specific Nextcloud user still exists, 2. there is no way for us to request the logo that you've put into your Nextcloud and I honestly don't want to implement the needed logic for this rather cosmetic request. PRs are welcome, of course!

You might be able to edit both things in the mastercontainer manually, though: 
The logo is stored in `/var/www/docker-aio/php/public/img/logo.svg`
You can edit the containers template manually and delete the login credentials in this file: `/var/www/docker-aio/php/templates/containers.twig`

See https://github.com/nextcloud/all-in-one/blob/fe99c3bc7809e3824858dbb5f93a22261d6b938f/php/templates/containers.twig#L70-L71
