### ISSUE TITLE
Documentation enhancement (readme.md)

### ISSUE THREAD

**Issue by Verhoeckx** [nextcloud/all-in-one#1734]
### Is your feature request related to a problem? Please describe. 
I just started reading the documentation and missed the following:

1. The documentation doesn't describe what `--sig-proxy=false` does (in the section `Explanation of the command`).
2. I miss a diagram of all the containers that are spawned and how they are connected to each other. This could give me (and others) valuable insight.
3. The section `Which ports are mandatory to be open in your firewall/router?` describes three port (443, 3478/tcp and 3478/udp), but then starts describing _six_ port (8080, 80, 8443, 443, 3478/tcp and 347/udp. Now which are truly mandatory? That's unclear to me.

### Describe the solution you'd like
It would be great if the documentation would answer question 1 and 3. A diagram of all spawned containers, and how they are connected with each other, would also be very helpful.

**Comment by Verhoeckx** [comment]
About the second point: if I know which containers are spawned and what their port numbers are, I could make a diagram similar to the image below (which still is work in progress). I could use the colours of the website of Nexctloud.


![Complete setup](https://user-images.githubusercontent.com/64807887/212216581-cef85e48-56e3-473e-a345-a33a5a337bd8.png)

**Comment by ManOki** [comment]
>     1. The documentation doesn't describe what `--sig-proxy=false` does (in the section `Explanation of the command`).

This is a `docker run` [command option](https://docs.docker.com/engine/reference/commandline/container_run/).

>     2. I miss a diagram of all the containers that are spawned and how they are connected to each other. This could give me (and others) valuable insight.

See [manual-install](https://github.com/nextcloud/all-in-one/tree/main/manual-install), especially the latest.yml (aka. docker-compose.yml). All containers except the mastercontainer are listed there including their ports. Note that not every container is mandatory, e.g., you don't need imaginary. So there are a lot of variants. The internal connection may be revealed from the `depends_on` part of the latest.yml file.

>     3. The section `Which ports are mandatory to be open in your firewall/router?` describes three port (443, 3478/tcp and 3478/udp), but then starts describing _six_ port (8080, 80, 8443, 443, 3478/tcp and 347/udp. Now which are truly mandatory? That's unclear to me.

The three ports (443, 3478 tcp+udp) have to be available outside of your host machine/home network to make nextcloud itself work correctly. So you _have to_ open them in your firewall or router. The other ports are optional due to their described functionality:

- if you have no other setup, you might directly use the internal ACME functionality of AIO to get a valid SSL certificate and therefore need to open port 80
- if you want access to the mastercontainer outside of your host machine you have to open port 8443
- other port 8080 is 'just' for internal reason/initial setup and should not be open to the public (use 8443 for public access)
