### ISSUE TITLE
Feature: Install Options

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#183]
Allow 

- Nextcloud Talk 
- Nextcloud Office 
- Nextcloud Dashboard 
- Nextcloud Set Status

to be **optional** for people that just use nextcloud for cloud file storage

**Comment by szaimen** [comment]
Hi there 👋

> * Nextcloud Talk
> * Nextcloud Office

Since those two are core features of Nextcloud AIO, we will not make them optional.
You should be able to limit the usage of the talk app to specific groups inside the talk admin settings (same for Nextcloud Office in the Office admin settings).

> * Nextcloud Dashboard
> * Nextcloud Set Status

Those two are provided by Nextcloud server by default. We will also not make those two optional, but you can simply disable those two apps in the apps managment interface of your server.
