### ISSUE TITLE
must NC AIO be set up again?

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#236]
When NC AIO Beta is set up and goes into stable version, does NC AIO need to be set up again to ensure all functions and best security or is it enough to make updates?

**Comment by szaimen** [comment]
You will be able to simply upgrade to the stable version when it comes out.

**Comment by R7JANV1** [comment]
Does this have any disadvantages? For example, the setup of NC AIO from a few months ago is protected with a 6 word password but now 8 words are used.

**Comment by szaimen** [comment]
> Does this have any disadvantages? For example, the setup of NC AIO from a few months ago is protected with a 6 word password but now 8 words are used.

This will be probably the only disadvantage that comes to my mind regarding security. 

Small hint regarding this: you can change the password or make it longer in `/var/lib/docker/volumes/nextcloud_aio_mastercontainer/_data/data/configuration.json` but I would not recommend it because you might break your instance when making a mistake while editing the file manually.
