### ISSUE TITLE
Delete Backups

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#278]
Add the function to delete the backups that are no longer needed in the Nextcloud AIO interface.

**Comment by szaimen** [comment]
Hi, why do you need this feature?

**Comment by R7JANV1** [comment]
To free space and delete files completely

**Comment by szaimen** [comment]
Since borg is fortunately very efficient in storing files and we already prune the backup archives regularly, I disagree that this is a must have feature for the AIO interface. I'll add some docs how to do this manually though.

**Comment by R7JANV1** [comment]
I understand what you're thinking, but I think it's also a security issue.  In order to delete backups remotely you would have to have access to the server via SSH and open port 30 just so that backups can be deleted. I think this is a major security gap that could be avoided by implementing it in the AIO interface.

 The other question would be why not add this feature?

**Comment by szaimen** [comment]
> I understand what you're thinking, but I think it's also a security issue. In order to delete backups remotely you would have to have access to the server via SSH and open port 30 just so that backups can be deleted. I think this is a major security gap that could be avoided by implementing it in the AIO interface.

You must have had some SSH access (or direct access) to the server in the first place in order to be able to install AIO so you can still go that way. 

Honestly I simply don't want to clutter the interface with that. Backups should simply not be deleted manually, imo.

For you to understand: I now run borg backups since a year or so on my personal server and I never needed the option to delete an archive manually since borg it is very efficient and the retention policy is in place as said before.

**Comment by R7JANV1** [comment]
I would be more happy about the function, but then adding it to the documentation is very helpful.
