### ISSUE TITLE
Manual install not working anymore

### ISSUE THREAD

**Issue by SecJoe** [nextcloud/all-in-one#3088]
### Steps to reproduce
Install Nextcloud-AIO like described in the readme: https://github.com/nextcloud/all-in-one/tree/main/manual-install

### Expected behavior 
Everything should work

### Actual behavior 
After starting via docker compose, i get the following error message:
```
$ sudo docker compose up
no such service: nextcloud-aio-imaginary
```

The docu also uses the old "docker-compose" binary [which is deprecated](https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose) and not the new "docker compose". Maybe the new docker compose needs an adjusted .yaml. 

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
6.4.0 (Current version)

#### Current channel 
Stable

**Comment by Zoey2936** [comment]
docker-compose is not deprecated, docker-compose v1 is deprecated...
![grafik](https://github.com/nextcloud/all-in-one/assets/75573284/4d7184d5-c5a6-417a-bac0-77c1ebb04e63)

The error you get must be something different

**Comment by Zoey2936** [comment]
seems to be a bug in docker-compose v2.20.x, just install docker-compose v2.19.1:
`curl -L https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s | tr [:upper:] [:lower:])-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose` and use `docker-compose` instead of `docker compose` for your commands
