### ISSUE TITLE
Automatically start container after backup

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#316]
Add that after the backup the containers start automatically.
Especially interesting for scheduled updates.
Alternatively, a checkbox can be added to control this function.

**Comment by szaimen** [comment]
No, we will not add thid because you should already be able to click the start containers button while the backup is running. 

Also schedules backups are coming with https://github.com/nextcloud/all-in-one/issues/47 which will not need such a button because it will automatically start the containers after the backup is done.
