### ISSUE TITLE
SKIP_DOMAIN_VALIDATION doesn't work

### ISSUE THREAD

**Issue by Acsigen** [nextcloud/all-in-one#3947]
### Steps to reproduce
1. Configure `SKIP_DOMAIN_VALIDATION=true` inside the docker compose file
2. Start the container
3. Access the AIO interface on my.local.domain:8443 while observing the logs

### Expected behavior 

I should be able to access the interface without any issue

### Actual behavior 
I get the following error message and I cannot access the web interface.

`{"level":"error","ts":1702917177.8639646,"logger":"tls.obtain","msg":"will retry","error":"[my.local.domain] Obtain: subject does not qualify for a public certificate: my.local.domain","attempt":2,"retrying_in":120,"elapsed":60.005646307,"max_duration":2592000}`

### Host OS 
Ubuntu 22.04 on WSL2. Also tried on Raspbery PI 4B and an Ubuntu 22.04 VM

#### Nextcloud AIO version 
Latest available within the docker compose file.

**Comment by Zoey2936** [comment]
did you followed https://github.com/nextcloud/all-in-one/blob/main/local-instance.md?

**Comment by Acsigen** [comment]
Yes, I receive the same error. I even tried with `extra_hosts` and it has the same behaviour

**Comment by Zoey2936** [comment]
Please share your compose file / docker run command

**Comment by uchiit** [comment]
I believe that this is not a SKIP_DOMAIN_VALIDATION error but AIO mastercontainer certificate issue error.

Just try to connect to port 8080 instead of 8443. Yes, it will be unencrypted, but AIO can't work with self-signed certificates on port 8443 at all. AIO wants to connect to Let's Encrypt for publicly issued certificate and if you will not provide a correct AIO domain name, AIO will not receive this certificate from Let's Encrypt and will not give you a possibility to connect to platform/container management interface in encrypted stile due to absence of correctly signed certificate.

In your case domain validation is skipped and this mean that AIO will not receive certificate from Let's Encrypt, which mean that port 8443 will be unavailable due to absence of certificate.

**Comment by Acsigen** [comment]
> > If you use `docker run` please use `--name nextcloud-aio-mastercontainer` inside the command, before the image name.
> > If you use docker compose, please add `container_name: "nextcloud-aio-mastercontainer"` to the configuration. Also do not rename the service.
> 
> container_name: nextcloud-aio-mastercontainer is already in the docker-compose file. I've used the exact docker-compose file the Readme says here: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-run-aio-with-portainer

This has fixed the issue. Thank you!
