### ISSUE TITLE
Documentation: Access / editing files via sftp

### ISSUE THREAD

**Issue by TheNomad11** [nextcloud/all-in-one#71]
Noob alert! Since this project is aimed at beginners: Some stuff is different when using Docker than using the standard install. The documents from the NC instance seem to reside in `/var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data` but editing them there directly via sftp or ssh does not work. Files I create via ssh don't show up in the NC interface. So: How can I do this (for the rare case I might need to do so)? I have become familiar with docker-compose where directories are mapped but here it is different again. 

Don't worry, I'll be learning more about Docker, this is just a general remark for making AIO more accessible for beginners!

Thanks so much for this project, I am testing it right now and consider using it for my main NC instance although it is still beta. Keep up your great work!

**Comment by szaimen** [comment]
Hi there 👋,

as with any other Nextcloud installation, you need to make sure that the files have the correct permissions. 

In this case, after copying your files you should be able to run `chown -R 33:0 root /var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data/*` in order to apply the correct permissions.

Afterwards, you need to make sure that the files get recognized by Nextclouds database. You can do this by running  `sudo docker exec -it nextcloud-aio-nextcloud php occ files:scan --all`.

Hope that works and explains everything :)

**Comment by TheNomad11** [comment]
Thanks! Now the files are there! It was no permission issue,  the last command did it!  I remember I used this command in old times after adding files to external storage.  Maybe we could add this question to the FAQ?
